import sys
from pathlib import Path

from zhimian.images import autogenerate_images, package_scene_images

# A tiny stand-in image generator: writes a placeholder PNG to --out.
FAKE_GEN = (
    "import argparse,sys\n"
    "p=argparse.ArgumentParser();p.add_argument('--prompt');p.add_argument('--out')\n"
    "a=p.parse_args()\n"
    "open(a.out,'wb').write(bytes.fromhex('89504e470d0a1a0a'))\n"
)


def _write_fake_gen(tmp_path: Path) -> Path:
    gen = tmp_path / "fake_gen.py"
    gen.write_text(FAKE_GEN, encoding="utf-8")
    return gen


def test_autogenerate_images_runs_command_per_prompt(tmp_path: Path):
    gen = _write_fake_gen(tmp_path)
    scenes = [
        {"id": "hook", "narration": "n1", "on_screen_text": "开场", "image_prompt": "a studio scene"},
        {"id": "plain", "narration": "n2", "on_screen_text": "无图"},  # no prompt -> skipped
    ]
    cmd = f'"{sys.executable}" "{gen}" --prompt {{prompt}} --out {{out}}'
    image_map, failures = autogenerate_images(scenes, cmd, tmp_path / "stage")

    assert set(image_map) == {"hook"}
    assert failures == []
    entry = image_map["hook"]
    assert Path(entry["path"]).is_file()
    assert Path(entry["path"]).is_absolute()  # downstream packaging resolves unambiguously
    assert entry["alt"] == "开场" and entry["prompt"] == "a studio scene"


def test_autogenerated_map_feeds_packaging(tmp_path: Path):
    gen = _write_fake_gen(tmp_path)
    scenes = [{"id": "hook", "narration": "n", "on_screen_text": "开场", "image_prompt": "x"}]
    cmd = f'"{sys.executable}" "{gen}" --prompt {{prompt}} --out {{out}}'
    image_map, _ = autogenerate_images(scenes, cmd, tmp_path / "stage")

    map_file = tmp_path / "map.json"
    import json
    map_file.write_text(json.dumps(image_map), encoding="utf-8")
    report = package_scene_images(scenes, map_file, tmp_path / "out")

    assert report["status"] == "ready" and report["attached_count"] == 1
    assert scenes[0]["image_file"] == "assets/generated/hook.png"


def test_autogenerate_records_failure_without_blocking(tmp_path: Path):
    scenes = [{"id": "hook", "narration": "n", "image_prompt": "x"}]
    # Command exits non-zero and writes nothing.
    cmd = f'"{sys.executable}" -c "import sys;sys.exit(3)"'
    image_map, failures = autogenerate_images(scenes, cmd, tmp_path / "stage")

    assert image_map == {}
    assert len(failures) == 1 and failures[0]["scene_id"] == "hook"
