import type { Style, Scene } from "./types";

export const STYLES: Record<string, Style> = {
  "dark-neon": {
    id: "dark-neon",
    name: "暗黑霓虹",
    description: "强烈冲击感，赛博朋克风格，适合开场钩子",
    bgGradient: "linear-gradient(135deg, #0a0a0f 0%, #14141c 50%, #0f0f1a 100%)",
    primaryColor: "#FF2D55",
    secondaryColor: "#00D4FF",
    accentColor: "#FFB300",
    textColor: "#F5F5FA",
    mutedColor: "#8888AA",
    borderColor: "rgba(255,45,85,0.4)",
    glowIntensity: "high",
  },
  "cream-editorial": {
    id: "cream-editorial",
    name: "米色编辑",
    description: "温暖学术感，适合深度讲解和公式展示",
    bgGradient: "linear-gradient(135deg, #F4EFE4 0%, #FFFDF7 50%, #F4EFE4 100%)",
    primaryColor: "#E83F32",
    secondaryColor: "#265CFF",
    accentColor: "#151515",
    textColor: "#151515",
    mutedColor: "#817B72",
    borderColor: "#E83F32",
    glowIntensity: "low",
  },
  "ref-comparison": {
    id: "ref-comparison",
    name: "红蓝对比",
    description: "清晰对比，红色表示问题，蓝色表示答案",
    bgGradient: "linear-gradient(135deg, #121212 0%, #1a1a1a 50%, #121212 100%)",
    primaryColor: "#E63946",
    secondaryColor: "#265CFF",
    accentColor: "#FFFFFF",
    textColor: "#FFFFFF",
    mutedColor: "#777777",
    borderColor: "#265CFF",
    glowIntensity: "medium",
  },
  "tech-glow": {
    id: "tech-glow",
    name: "科技流光",
    description: "现代科技感，绿色代码光效，适合技术讲解",
    bgGradient: "linear-gradient(135deg, #0d1b2a 0%, #1b263b 50%, #0d1b2a 100%)",
    primaryColor: "#00FF88",
    secondaryColor: "#00D4FF",
    accentColor: "#FF6B6B",
    textColor: "#E0E0E0",
    mutedColor: "#6B7280",
    borderColor: "rgba(0,255,136,0.3)",
    glowIntensity: "high",
  },
};

export const SCENES: Scene[] = [
  {
    id: "hook",
    title: "90%开口就答错",
    subtitle: "系统设计题｜一上来就堆模型就偏了",
    visualType: "comparison",
    leftLabel: "背答案",
    rightLabel: "讲机制",
    winner: "right",
  },
  {
    id: "intuition",
    title: "分层拆解",
    subtitle: "需求-接口-存储-计算-扩展",
    visualType: "flow",
    steps: ["问题入口", "关键变量", "底层机制", "落地取舍"],
  },
  {
    id: "principle",
    title: "论文证据",
    subtitle: "核心机制",
    visualType: "formula",
    tokens: ["问题", "=", "机制", "+", "证据", "+", "边界"],
  },
  {
    id: "followups",
    title: "追问链",
    subtitle: "追问链决定上限",
    visualType: "code",
    code: "Q1: 为什么这样设计？\nQ2: 复杂度/成本是多少？\nQ3: 边界情况会不会翻车？",
  },
  {
    id: "answer",
    title: "高分框架",
    subtitle: "结论 · 原理 · 取舍 · 落地",
    visualType: "process",
    steps: ["结论", "原理", "取舍", "落地"],
  },
  {
    id: "mistake",
    title: "避坑指南",
    subtitle: "别背术语，要讲为什么",
    visualType: "comparison",
    leftLabel: "术语很多",
    rightLabel: "因果清楚",
    winner: "right",
  },
];
